### ISSUE TITLE
could i only use this to predict the action by only input the personfeature and keypoint ?

### ISSUE THREAD

**Issue by shaldor0315** [google/next-prediction#11]

**Comment by JunweiLiang** [comment]
You'll need to change the code in models.py by removing other features in enc_h_list and enc_last_state_list. Also, you need to remove the trajectory decoder. Then re-train the model.

**Comment by shaldor0315** [comment]
Okay,I get it.thank you^_^




| |
何轶群
|
|
邮箱：hyq0315@yeah.net
|

签名由 网易邮箱大师 定制

On 12/03/2019 22:34, Junwei Liang wrote:

Closed #11.

**Comment by shaldor0315** [comment]
Hi,junwei.when I try to prepare the visual features,I can neither find the step5_person_appearance nor the step6 nor the step4..,I had try to find them in the other repo,but had no result.is this part not public?




| |
何轶群
|
|
邮箱：hyq0315@yeah.net
|

签名由 网易邮箱大师 定制

On 12/03/2019 22:55, shaldor0315 wrote:
Okay,I get it.thank you^_^




| |
何轶群
|
|
邮箱：hyq0315@yeah.net
|

签名由 网易邮箱大师 定制

On 12/03/2019 22:34, Junwei Liang wrote:

Closed #11.

**Comment by JunweiLiang** [comment]
They are in my fork: https://github.com/JunweiLiang/next-prediction/tree/master/code/prepare_data

**Comment by shaldor0315** [comment]
谢谢🙏🙏🙏




| |
何轶群
|
|
邮箱：hyq0315@yeah.net
|

签名由 网易邮箱大师 定制

On 12/14/2019 05:45, Junwei Liang wrote:

They are in my fork: https://github.com/JunweiLiang/next-prediction/tree/master/code/prepare_data

**Comment by shaldor0315** [comment]
hi,junwei! 
can you tell me the mapping relationship between the act_id to the real action in the project of next_prediction_master. and i know there are total 29 activities ans 1 background.the 29 acticity is as below:  Carry Close_Door Close_Trunk Crouch Enter Exit Gesture Interaction Load Object_Transfer Open_Door Open_Trunk PickUp PickUp_Person Pull Push Ride_Bike Run SetDown Sit Stand Talk Talk_phone Texting Touch Transport Unload User_tool Walk.

**Comment by JunweiLiang** [comment]
They are already in the code:
https://github.com/google/next-prediction/blob/master/code/utils.py#L35

**Comment by shaldor0315** [comment]
Okay!thank you!!




| |
何轶群
|
|
邮箱：hyq0315@yeah.net
|

签名由 网易邮箱大师 定制

On 03/05/2020 23:39, Junwei Liang wrote:

They are already in the code:
https://github.com/google/next-prediction/blob/master/code/utils.py#L35
