### ISSUE TITLE
regarding the preprocessed files

### ISSUE THREAD

**Issue by kashyaprakshith** [google/next-prediction#13]
in order to run the preprocessed.py file we need the traj_path and output_path and i have downloaded the pretrained model and prepared data where can i find the trajectory files and what path should i give to run the preprocessed.py 
and, for the output_path can i give any any path ?

**Comment by JunweiLiang** [comment]
Please follow the instructions in [TESTING.MD](https://github.com/google/next-prediction/blob/master/TESTING.md)．
Yes the output_path can be any path but then for training and testing you need to also use that path.

**Comment by JunweiLiang** [comment]
The trajectories (xy coordinates) are in next-data/final_annos/actev_annos/virat_2.5fps_resized_allfeature/
