### ISSUE TITLE
regarding the preprocess.py

### ISSUE THREAD

**Issue by kashyaprakshith** [google/next-prediction#14]
there is an error we are getting about the x_range and the preprocess.py is not running succesfully i have attached the image of the error it is showing please resolve my issue as soon as possible. 
![github error](https://user-images.githubusercontent.com/58388399/73135387-ae53c980-4041-11ea-8617-c453682a461d.png)

**Comment by JunweiLiang** [comment]
You are using python 3. Please refer to [here](https://github.com/google/next-prediction/blob/master/requirements.txt) for system requirements. A simple fix is to replace all "xrange" with "range".
