### ISSUE TITLE
What is the backbone network used in the pretrained object detector for the person behavior module?

### ISSUE THREAD

**Issue by malarsaravanan1991** [google/next-prediction#17]
Hey hi,
what is the backbone that you had used for the person detector in the person behavior module to extract CNN features for the person bounding boxes.?
Can you please let me know ,I am trying to compare your Activity mAP with my work. I did like to know more about the settings of the pretrained object detector you had used in the person behavior module.

**Comment by JunweiLiang** [comment]
We used the obj_v3 model from this [repo](https://github.com/JunweiLiang/Object_Detection_Tracking). It is basically a Faster RCNN model with Resnet-101 backbone (and dilated convolution) pretrained on MSCOCO and then finetuned on the VIRAT training set.
See [here](https://github.com/JunweiLiang/next-prediction/blob/master/code/prepare_data/README.md) for feature extraction.

**Comment by malarsaravanan1991** [comment]
Thank you.
