### ISSUE TITLE
regarding visualization the ActEV world coordinates

### ISSUE THREAD

**Issue by isaryo** [google/next-prediction#18]
Hi.
I would like to know how I can visualization the ActEV world coordinates.
So, I read next-prediction/code/baselines/ you wrote.
I have 2 questions.
1.When I run vis_world.py, What is argments?
2.What is homography matrix?

**Comment by isaryo** [comment]
now, I understand homography matrix.
I want to know 1. question.

**Comment by JunweiLiang** [comment]
I'll add to the README later.

**Comment by isaryo** [comment]
Thank you. I'm waiting for it.

**Comment by JunweiLiang** [comment]
Done. [README](https://github.com/JunweiLiang/next-prediction/tree/master/code/baselines)

**Comment by rashidch** [comment]
Hi! 
I cannot download homography matrix from this link : [https://next.cs.cmu.edu/data/072019_prepare_data/actev_homography.tgz](url). 

Can you kindly update the link?

Thank you.

**Comment by JunweiLiang** [comment]
You can try https://precognition.team/next/data/072019_prepare_data/actev_homography.tgz

**Comment by rashidch** [comment]
Hi,
I have a questione about prepared ActEV dataset available on this link: https://precognition.team/next/data/072019_prepare_data/072019_next_my_prepare.tgz

Although you mentioned in your next paper that you do not use homographic matrices, and that you use pixel values for the trajectory, I would like to confirm whether the prepared dataset available on the link above is in pixel coordinates or world coordinates.

**Comment by JunweiLiang** [comment]
These should be pixel coordinates
