### ISSUE TITLE
try to visualization

### ISSUE THREAD

**Issue by isaryo** [google/next-prediction#20]
No,good,,,I don't understand how to get predictions even though I try to it over and over..
I know you're frustrated because I'm true begginer.
I answered based on [this](https://github.com/JunweiLiang/social-distancing-prediction) to plot the path prediction using heatmap.
Please tell me how to save path predictions and activity predictions?

_Originally posted by @isaryo in https://github.com/google/next-prediction/issues/4#issuecomment-638006697_

**Comment by JunweiLiang** [comment]
Please do not open a new issue for the same question. Please refer to updates in #4.
