### ISSUE TITLE
Download ActEV Dataset

### ISSUE THREAD

**Issue by guofengpeng** [google/next-prediction#24]
你好大佬，看到这篇文章，我想试一把，但是发现下载数据集出现了问题，提供下载数据集的官网好像更新了，我没有找到下载的地方（大概率是我不太理解国外网站的架构），能帮我看下么，谢谢啦。
还有，这个数据集是不是包括视频，图片和标注好的文件呢？如果没有图片的话是不是也提供了脚本来制作，保证和前面的标注文档相对应呢？谢谢啦

**Comment by JunweiLiang** [comment]
ActEV的数据集在这里：https://gitlab.kitware.com/actev/actev-data-repo
你可以根据上面的指示下载。这个数据集包含视频和文本标注。可以根据[这里](https://github.com/JunweiLiang/next-prediction/blob/master/code/prepare_data/README.md#step-1-get-the-videos)预处理数据。

**Comment by guofengpeng** [comment]
有没有更方便的方法，直接就能下载的（标注文件actev-v1-drop4-yaml.tgz我已经按照您的说明下载解压了），我这边网络受限，git不能执行git pull，也不能用百度云或者其他的网盘，比较痛苦

**Comment by JunweiLiang** [comment]
也许另外一个渠道是去[VIRAT官网](https://viratdata.org/)下载原始视频：https://data.kitware.com/#collection/56f56db28d777f753209ba9f/folder/56f57e748d777f753209bed6

**Comment by guofengpeng** [comment]
很奇怪，我都是直接下载的，这两天尝试了五次，但是每次下载成功后都不能解压，原因一直是“压缩文件已损坏”，很奇怪，我的服务器使用的国外，应该不是墙的问题。

**Comment by guofengpeng** [comment]
很奇怪，我都是直接下载的，这两天尝试了五次，但是每次下载成功后都不能解压，原因一直是“压缩文件已损坏”，很奇怪，我的服务器使用的国外，应该不是墙的问题。

**Comment by guofengpeng** [comment]
很奇怪，我都是直接下载的，这两天尝试了五次，但是每次下载成功后都不能解压，原因一直是“压缩文件已损坏”，很奇怪，我的服务器使用的国外，应该不是墙的问题。
过程是点击您给的网站，列表里我勾选所有的，下拉箭头点“download checked Resources”，然后开始下载，会有名为“Resources”的zip文件，文件大小约3G，但是下载成功后，解压屡屡都是错误的，很奇怪

**Comment by JunweiLiang** [comment]
你可以发邮件问问数据提供方
