### ISSUE TITLE
How to get prepared data?

### ISSUE THREAD

**Issue by tom728** [google/next-prediction#26]
Hello, how are the three files in this file (scripts/download_prepared_data.s) made? The project page of step 1 no longer exists（ https://github.com/google/next-prediction/blob/master/TRAINING.md ）. In addition, how to make your own data set to label and make the above three files? Thank you!

**Comment by JunweiLiang** [comment]
Hi, 
The links are still available. To extract features yourself, follow this existing guide: https://github.com/google/next-prediction#preparing-rich-visual-features
