### ISSUE TITLE
exp mask

### ISSUE THREAD

**Issue by bbidong** [google/next-prediction#29]
the 'exp_mask' defined in 'models.py' is to mask the useless features,  then return the vector as the input of softmax fuction. 
![image](https://user-images.githubusercontent.com/35252861/103474578-33159e80-4de0-11eb-9dcc-21f1dacd91ec.png)

suppose val is 1, mask is 0 or 1,  then how to make a difference between 
$ (1+0) * -1e30 $ and $ (1+1) * -1e30 $  ,  

Looking forward to the answer  !

**Comment by JunweiLiang** [comment]
Doesn't matter what val is actually. And the multiply is before tf.add. Think about this case: val is a vector of size 3, [2.4, -5.0, 0.23], and mask is [1, 1, 0] (we use 0 to mark unused positions). so we have (val + [0, 0, -1e30]), so the last dimension of val's would become a very negative number, no mater what its original value is (unless it is a very positive number, which is unlikely).
