### ISSUE TITLE
ActeV train/test split

### ISSUE THREAD

**Issue by atanas1054** [google/next-prediction#3]
Hello,

Can you please confirm that you use the following data for the results in your paper?

TRAINING:

v1-training/
v1-training/0000
v1-training/0000/VIRAT_S_000000
v1-training/0000/VIRAT_S_000001
v1-training/0000/VIRAT_S_000002
v1-training/0000/VIRAT_S_000005
v1-training/0002
v1-training/0002/VIRAT_S_000200_03_000657_000899
v1-training/0002/VIRAT_S_000200_05_001525_001575
v1-training/0002/VIRAT_S_000201_03_000640_000672
v1-training/0002/VIRAT_S_000201_05_001081_001215
v1-training/0002/VIRAT_S_000201_06_001354_001397
v1-training/0002/VIRAT_S_000201_07_001485_001581
v1-training/0002/VIRAT_S_000201_08_001652_001838
v1-training/0002/VIRAT_S_000202_02_001527_001560
v1-training/0002/VIRAT_S_000202_03_001577_001611
v1-training/0002/VIRAT_S_000202_04_001704_001746
v1-training/0002/VIRAT_S_000203_03_000736_000785
v1-training/0002/VIRAT_S_000203_05_001122_001159
v1-training/0002/VIRAT_S_000203_06_001206_001266
v1-training/0002/VIRAT_S_000203_07_001341_001458
v1-training/0002/VIRAT_S_000204_00_000000_000109
v1-training/0002/VIRAT_S_000204_03_000667_000703
v1-training/0002/VIRAT_S_000204_04_000738_000977
v1-training/0002/VIRAT_S_000204_05_001334_001520
v1-training/0002/VIRAT_S_000205_00_000065_000149
v1-training/0002/VIRAT_S_000205_04_000927_001057
v1-training/0002/VIRAT_S_000205_07_001761_001804
v1-training/0002/VIRAT_S_000206_03_000500_000556
v1-training/0002/VIRAT_S_000206_04_000710_000779
v1-training/0002/VIRAT_S_000206_07_001501_001600
v1-training/0002/VIRAT_S_000207_01_000094_000156
v1-training/0002/VIRAT_S_000207_04_000902_000934
v1-training/0400
v1-training/0400/VIRAT_S_040000_02_000111_000145
v1-training/0400/VIRAT_S_040000_03_000221_000372
v1-training/0400/VIRAT_S_040000_05_000668_000703
v1-training/0400/VIRAT_S_040001_00_000035_000319
v1-training/0400/VIRAT_S_040001_01_000448_001101
v1-training/0400/VIRAT_S_040001_03_001531_001595
v1-training/0400/VIRAT_S_040002_03_001525_001569
v1-training/0400/VIRAT_S_040003_04_000758_001118
v1-training/0400/VIRAT_S_040003_06_001441_001518
v1-training/0400/VIRAT_S_040004_00_000011_000093
v1-training/0400/VIRAT_S_040005_00_000003_000058
v1-training/0400/VIRAT_S_040005_07_001026_001223
v1-training/0401
v1-training/0401/VIRAT_S_040100_01_000347_000432
v1-training/0401/VIRAT_S_040101_02_000224_000440
v1-training/0401/VIRAT_S_040101_03_000460_000551
v1-training/0401/VIRAT_S_040101_04_000562_000679
v1-training/0401/VIRAT_S_040102_08_000986_001090
v1-training/0401/VIRAT_S_040102_10_001258_001408
v1-training/0401/VIRAT_S_040102_13_001557_001589
v1-training/0401/VIRAT_S_040103_05_000729_000804
v1-training/0401/VIRAT_S_040103_07_001011_001093
v1-training/0401/VIRAT_S_040103_08_001475_001512
v1-training/0401/VIRAT_S_040104_00_000120_000224
v1-training/0401/VIRAT_S_040104_01_000227_000457
v1-training/0401/VIRAT_S_040104_04_000854_000934
v1-training/0401/VIRAT_S_040104_05_000939_001116
v1-training/0401/VIRAT_S_040104_06_001121_001241
v1-training/0401/VIRAT_S_040104_08_001353_001470
v1-training/0500
v1-training/0500/VIRAT_S_050000_01_000207_000361
v1-training/0500/VIRAT_S_050000_04_000640_000690
v1-training/0500/VIRAT_S_050000_05_000696_000732
v1-training/0500/VIRAT_S_050000_07_001014_001126
v1-training/0500/VIRAT_S_050000_10_001462_001491
v1-training/0500/VIRAT_S_050000_12_001591_001619

TESTING:
v1-validate/
v1-validate/0000
v1-validate/0000/VIRAT_S_000007
v1-validate/0000/VIRAT_S_000008
v1-validate/0002
v1-validate/0002/VIRAT_S_000200_00_000100_000171
v1-validate/0002/VIRAT_S_000200_02_000479_000635
v1-validate/0002/VIRAT_S_000201_00_000018_000380
v1-validate/0002/VIRAT_S_000201_01_000384_000589
v1-validate/0002/VIRAT_S_000201_02_000590_000623
v1-validate/0002/VIRAT_S_000201_04_000682_000822
v1-validate/0002/VIRAT_S_000203_01_000171_000345
v1-validate/0002/VIRAT_S_000203_08_001702_001734
v1-validate/0002/VIRAT_S_000204_07_001577_001611
v1-validate/0002/VIRAT_S_000204_09_001768_001849
v1-validate/0002/VIRAT_S_000205_01_000197_000342
v1-validate/0002/VIRAT_S_000205_02_000409_000566
v1-validate/0002/VIRAT_S_000205_03_000860_000922
v1-validate/0002/VIRAT_S_000205_05_001092_001124
v1-validate/0002/VIRAT_S_000205_06_001566_001631
v1-validate/0002/VIRAT_S_000206_00_000025_000058
v1-validate/0002/VIRAT_S_000206_01_000148_000184
v1-validate/0002/VIRAT_S_000206_02_000294_000327
v1-validate/0002/VIRAT_S_000206_08_001618_001712
v1-validate/0002/VIRAT_S_000207_02_000498_000530
v1-validate/0002/VIRAT_S_000207_03_000556_000590
v1-validate/0400
v1-validate/0400/VIRAT_S_040000_00_000000_000036
v1-validate/0400/VIRAT_S_040000_01_000042_000099
v1-validate/0400/VIRAT_S_040000_04_000532_000622
v1-validate/0400/VIRAT_S_040000_08_001084_001190
v1-validate/0400/VIRAT_S_040000_09_001194_001574
v1-validate/0400/VIRAT_S_040003_00_000000_000072
v1-validate/0400/VIRAT_S_040003_01_000083_000193
v1-validate/0400/VIRAT_S_040003_02_000197_000552
v1-validate/0400/VIRAT_S_040005_06_000886_001016
v1-validate/0400/VIRAT_S_040005_08_001225_001276
v1-validate/0401
v1-validate/0401/VIRAT_S_040100_03_000496_000559
v1-validate/0401/VIRAT_S_040100_04_000626_000689
v1-validate/0401/VIRAT_S_040100_05_000696_000762
v1-validate/0401/VIRAT_S_040100_06_000767_000988
v1-validate/0401/VIRAT_S_040100_07_001043_001099
v1-validate/0401/VIRAT_S_040100_08_001103_001181
v1-validate/0401/VIRAT_S_040100_09_001186_001533
v1-validate/0401/VIRAT_S_040101_05_000722_001547
v1-validate/0401/VIRAT_S_040101_06_001557_001590
v1-validate/0401/VIRAT_S_040102_04_000596_000689
v1-validate/0401/VIRAT_S_040102_06_000849_000908
v1-validate/0401/VIRAT_S_040102_07_000916_000983
v1-validate/0401/VIRAT_S_040103_00_000000_000120
v1-validate/0401/VIRAT_S_040103_01_000132_000195
v1-validate/0401/VIRAT_S_040103_02_000199_000279
v1-validate/0401/VIRAT_S_040103_03_000284_000425
v1-validate/0401/VIRAT_S_040103_06_000836_000909
v1-validate/0401/VIRAT_S_040104_07_001268_001348
v1-validate/0500
v1-validate/0500/VIRAT_S_050000_06_000908_000970
v1-validate/0500/VIRAT_S_050000_08_001235_001295
v1-validate/0500/VIRAT_S_050000_09_001310_001373
v1-validate/0500/VIRAT_S_050000_11_001530_001576

If I just use a simple linear regressor with the above data (sampled at 2.5 fps, 8 obs length, 12 prediction length) to predict the person's trajectory, I get ADE = 10.44  and FDE  = 21.63. This is much lower than what is reported in the paper so I am trying to figure out what I am doing wrong.

**Comment by saruvora** [comment]
Hi can I know which linear regressor do you use ? please can you share your algorithm?

**Comment by atanas1054** [comment]
I use linear_model from sklearn

After I preprocess the data I have something like this:

8 observed frames, 12 predicted frames and 4 bounding box coordinates

```
train_input = [N_trajectories, 8, 4]
train_output = [N_trajectories, 12, 4]
test_input = [M_trajectories, 8, 4]
test_output = [M_trajectories, 12, 4]

train_input = train_input.reshape(N_trajectories, 8*4)
train_output = train_output.reshape(N_trajectories, 12*4)

regr = linear_model.LinearRegression()
regr.fit(train_input, train_output)

test_input = test_input.reshape(N_trajectories, 8*4)
prediction = regr.predict(test_input)

prediction = prediction.reshape(N_trajectories, 12, 4)
```

I then take the middle point of the predicted bounding boxes (in pixels) and compute ADE and FDE.

**Comment by JunweiLiang** [comment]
Hi,

1. You can get our train/val/test in the preprocessed data that you can download according to [TRAINING.md](https://github.com/google/next-prediction/blob/master/TRAINING.md) in next-data/final_annos/actev_annos/virat_2.5fps_resized_allfeature/

2. I think the difference in preprocessing the data causes the performance difference as we measure ADE/FDE in pixels. I suggest you use our preprocessed coordinates in next-data/final_annos/actev_annos/virat_2.5fps_resized_allfeature/
Each file is in the following format:
frame_index, person_id, x, y
0       52.0    1422.000000     716.000000
Also, I suggest you try the ETH/UCY data in next-data/final_annos/ucyeth_annos/original_trajs/ as well. They are in meters.

3. I don't have time to release our preprocessing yet. Here are some important details about preprocessing the data on ActEV dataset as mentioned in the paper:

(1) We resize all videos to 1920x1080 resolution (0002 scene videos originally are 1280x720 resolution). So the pixel-based model could see somewhat consistent data.

(2) We drop 12 frames after getting one frame (so just sorted_frames[::12]):
```
# newdata is a list with each row (frame_index, person_id, x, y)
newdata.sort(key=operator.itemgetter(0))
frames = np.unique([one[0] for one in newdata]).tolist()
# uniformly drop frames
frames_to_keep = frames[::args.drop_frame]
drop_newdata = [one for one in newdata if one[0] in frames_to_keep]
newdata = drop_newdata
```

(3) We use the "foot" position of the bounding box as trajectory coordinates (middle point of the bottom line).

Let me know how it goes.
Thanks.

**Comment by saruvora** [comment]
> I use linear_model from sklearn
> 
> After I preprocess the data I have something like this:
> 
> 8 observed frames, 12 predicted frames and 4 bounding box coordinates
> 
> ```
> train_input = [N_trajectories, 8, 4]
> train_output = [N_trajectories, 12, 4]
> test_input = [M_trajectories, 8, 4]
> test_output = [M_trajectories, 12, 4]
> 
> train_input = train_input.reshape(N_trajectories, 8*4)
> train_output = train_output.reshape(N_trajectories, 12*4)
> 
> regr = linear_model.LinearRegression()
> regr.fit(train_input, train_output)
> 
> test_input = test_input.reshape(N_trajectories, 8*4)
> prediction = regr.predict(test_input)
> 
> prediction = prediction.reshape(N_trajectories, 12, 4)
> ```
> 
> I then take the middle point of the predicted bounding boxes (in pixels) and compute ADE and FDE.

Thank you very much for the code will check it out :)

**Comment by JunweiLiang** [comment]
Added notes for the prepared data [here](https://github.com/google/next-prediction/blob/master/NOTES.md).

**Comment by JunweiLiang** [comment]
Closing this for now. Please report when you have results.
