### ISSUE TITLE
Visualization of activity prediction

### ISSUE THREAD

**Issue by thatsvenki038** [google/next-prediction#40]
I have used the social distancing repo to plot the trajectories and future trajectories. How could i plot future activity?
Do i need train any activity detection model or the current code base does it? There is some code in the social distance repo in inference suggests the activity model is not used.(please check the commented lines below). can this code be used to extend next activity prediction in this repo? 

Also, 
1. What should i do to extend the object detection classes to vehicles as well? Currently it detects only persons. and interactions?
2. where are the activity prediction matrices stored?
 """
              # ignore activity prediction due to low mAP
              # 2.2 Plot the activity prediction if there are high confidence
              # a list of [act_name, prob], sorted
              act_pred = this_pred["act_pred"]

              # only plot activities of the following if they are in the top-3
              plot_only_act = social_distancing_violation_acts
              # add all act probs
              this_plot_acts = [
                  (act_name, act_prob)
                  for act_name, act_prob in act_pred
                  if act_name in plot_only_act]
              prob_sum = sum([prob for _, prob in this_plot_acts])
              """

**Comment by JunweiLiang** [comment]
The current code base does the activity prediction as well. Please move this question to the social distancing repo.
