### ISSUE TITLE
ETHUCY Dataset  test split size

### ISSUE THREAD

**Issue by rashidch** [google/next-prediction#42]
Hi,
I have downloaded the ETHUCY dataset from this link: wget https://precognition.team/next/data/final_annos.tgz -O next-data/final_annos.tgz 

However, compared to the latest works, the size of the test set is very small for the following scenes: ETH 181 samples, hotel 1053 test samples, and zara1 2253.

Was the peeking into the future model in the paper evaluated using these test set samples from ETHUCY?

**Comment by JunweiLiang** [comment]
These are the samples in ETHUCY that have corresponding videos.
