### ISSUE TITLE
Train and test on own dataset

### ISSUE THREAD

**Issue by ilyes-hm** [google/next-prediction#5]
Hi,
I am really interested in your work.
I am wondering if I am able to train or just test pre-trained models on my own dataset?
Thank you in advance.

**Comment by JunweiLiang** [comment]
Thanks. You can use the pre-trained models directly if the datasets are not too different (e.g., not moving cameras). You will need to extract features using pre-trained models according to [this issue](https://github.com/google/next-prediction/issues/1) for training and testing.
