### ISSUE TITLE
extract of boxes

### ISSUE THREAD

**Issue by bbidong** [google/next-prediction#6]
the Problem Formulation part in paper says "Based on the coordinates, we can automatically extract their bounding boxes" . I wonder how to get it in eth/ucy dataset? Especially how to get the box of human target because the coordinates provided by eth/ucy dataset is in world plane 
Thanks for your repo!

**Comment by JunweiLiang** [comment]
Hi,

The ETH/UCY dataset comes with the homography matrices so we could use that to map world coordinates to pixel coordinates. Example pseudo code for Hotel:
```
# input: H.txt & biwi_hotel.txt
# 1. load the homography matrix
# 2. _, h = cv2.invert(np.array(h)) # invert the matrix for meter to pixel
# 3. pixel_points = cv2.perspectiveTransform(np.array([[[x_meter,y_meter]]]), h)
# x_pixel,y_pixel = np.squeeze(pixel_points)
```
Then, we resize all videos (and the pixel coordinates) to 720x576. The person boxes are extracted based on average size of people in the videos:
```
# point_pos means where the trajectory points are located.
video2box = {
	"seq_eth":lambda xy: make_box(xy,w=20,h=40,point_pos="head"),
	"seq_hotel":lambda xy:make_box(xy,w=80,h=50,point_pos="head"),
	"crowds_zara01":lambda xy:make_box(xy,w=50,h=80,point_pos="feet"),
	"crowds_zara02":lambda xy:make_box(xy,w=50,h=80,point_pos="head"),
	"students003":lambda xy:make_box(xy,w=50,h=80,point_pos="feet")
}
```

**Comment by jagmonroy** [comment]
Hi! I'm working with zara2, I understand that is part of the ETH/UCY dataset. You comment previously that are homography matrices available, is there any place where I can find them? 

Regards!

**Comment by JunweiLiang** [comment]
They are in the rar files.

https://graphics.cs.ucy.ac.cy/research/downloads/crowd-data

**Comment by bbidong** [comment]
It is saved in H.txt

**Comment by jagmonroy** [comment]
I get some rar files, but they only contain splines ):

**Comment by MZ82020** [comment]
> 
Hello @JunweiLiang, 

For the perspective transform function: pixel_points = cv2.perspectiveTransform(np.array([[[x_meter,y_meter]]]), h)
what refers x_meter and y_meter please? 
I have always errors in this function.

**Comment by JunweiLiang** [comment]
The x_meter and y_meter are the original coordinates of the ETH/UCY dataset files, which are world coordinates in meters.

**Comment by MZ82020** [comment]
> The x_meter and y_meter are the original coordinates of the ETH/UCY dataset files, which are world coordinates in meters.

where can I find them please?

**Comment by JunweiLiang** [comment]
> They are in the rar files.
> 
> https://graphics.cs.ucy.ac.cy/research/downloads/crowd-data

**Comment by MZ82020** [comment]
For my case, I want to visualize the observed, predicted and groundtruth trajectories after the test. 
How can I do that please?

**Comment by JunweiLiang** [comment]
https://github.com/google/next-prediction/issues/4

**Comment by MZ82020** [comment]
in my case, it's different. I have x_obs & y_obs for time 0 to 7 and x_pred & y_pred for time 0 to 11.
I want to do the visualization of the trajectories; do I have to do the conversion with the perspective transform too? 
or how can I do it please? do you have an idea

Thanks

**Comment by JunweiLiang** [comment]
If your model is trained with pixel coordinates, then you do not need to convert them.
