### ISSUE TITLE
How can I run this code and test it on video? 

### ISSUE THREAD

**Issue by aalzooke** [google/next-prediction#7]
Can you please explain how to test this code using my own video or webcam? 
thank you

**Comment by JunweiLiang** [comment]
Please refer to [this issue](https://github.com/google/next-prediction/issues/5) and [this issue](https://github.com/google/next-prediction/issues/1).

We may release this part of the code in a few months.

**Comment by rouge012** [comment]
Hi! Did you publish this part of the code which can infer my own video?
Thank you!

**Comment by JunweiLiang** [comment]
https://github.com/JunweiLiang/social-distancing-prediction
